// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMXmnjEa2XNYJM7UjnArSOsI8cxwWnwA',
    appId: '1:266768433547:web:61860b2983735d8a10ef8e',
    messagingSenderId: '266768433547',
    projectId: 'jwhrr-a0345',
    authDomain: 'jwhrr-a0345.firebaseapp.com',
    storageBucket: 'jwhrr-a0345.appspot.com',
    measurementId: 'G-SWQ4Q38C2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwkOKHpWfKrIeA5PiC3ei98ajvlJhwqU',
    appId: '1:266768433547:android:ee4464a1bc8f7f8510ef8e',
    messagingSenderId: '266768433547',
    projectId: 'jwhrr-a0345',
    storageBucket: 'jwhrr-a0345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbspXBR1H9iDMf2cQGTWIHuabl7eygss0',
    appId: '1:266768433547:ios:84bf2e97e900ed4a10ef8e',
    messagingSenderId: '266768433547',
    projectId: 'jwhrr-a0345',
    storageBucket: 'jwhrr-a0345.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbspXBR1H9iDMf2cQGTWIHuabl7eygss0',
    appId: '1:266768433547:ios:84bf2e97e900ed4a10ef8e',
    messagingSenderId: '266768433547',
    projectId: 'jwhrr-a0345',
    storageBucket: 'jwhrr-a0345.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlMXmnjEa2XNYJM7UjnArSOsI8cxwWnwA',
    appId: '1:266768433547:web:fd90d5c1da8d2b5c10ef8e',
    messagingSenderId: '266768433547',
    projectId: 'jwhrr-a0345',
    authDomain: 'jwhrr-a0345.firebaseapp.com',
    storageBucket: 'jwhrr-a0345.appspot.com',
    measurementId: 'G-SC3BZ42HVK',
  );

}